import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

const getBase64FromUrl = async (url: string): Promise<string> => {
    const data = await fetch(url);
    const blob = await data.blob();
    return new Promise((resolve) => {
        const reader = new FileReader();
        reader.readAsDataURL(blob);
        reader.onloadend = () => {
            const base64data = reader.result;
            resolve(base64data as string);
        };
    });
};

export const exportProductPDF = async (product: any) => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();

    // Header Branding
    doc.setFillColor(30, 41, 59); // Slate 800
    doc.rect(0, 0, pageWidth, 40, 'F');

    doc.setFontSize(24);
    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.text("PRODUCT REPORT", 14, 25);

    doc.setFontSize(10);
    doc.setTextColor(200, 200, 200);
    doc.text(`Official Document - Generated on: ${new Date().toLocaleString("th-TH")}`, 14, 33);

    let currentY = 55;

    // Add image if available with beautiful framing
    const imageUrl = product.displayImage || product.imageUrl;
    if (imageUrl) {
        try {
            const base64 = await getBase64FromUrl(imageUrl);
            const imgWidth = 80;
            const imgHeight = 60;
            const xPos = (pageWidth - imgWidth) / 2;

            // Image Frame/Background
            doc.setDrawColor(241, 245, 249); // Slate 100
            doc.setFillColor(252, 253, 254);
            doc.roundedRect(xPos - 5, currentY - 5, imgWidth + 10, imgHeight + 10, 5, 5, 'FD');

            // Actual Image
            doc.addImage(base64, 'JPEG', xPos, currentY, imgWidth, imgHeight);

            currentY += imgHeight + 20;
        } catch (error) {
            console.error("Could not add image to PDF:", error);
            currentY += 10;
        }
    }

    // Detail Section Header
    doc.setFontSize(14);
    doc.setTextColor(30, 41, 59);
    doc.setFont("helvetica", "bold");
    doc.text("TECHNICAL SPECIFICATIONS", 14, currentY - 5);

    autoTable(doc, {
        startY: currentY,
        head: [["Attribute", "Information"]],
        body: [
            ["Object ID", `#${product.id}`],
            ["Model Name", product.productName || "-"],
            ["Category", product.category || "-"],
            ["Lot Tracking", product.lot || "-"],
            ["Market Price", `฿${product.confirmedPrice?.toLocaleString() || "0"}`],
            ["Inventory Status", product.status || "-"],
            ["Production Year", product.year || "-"],
            ["Registered Consignor", product.consignorName || "-"]
        ],
        theme: 'grid',
        headStyles: {
            fillColor: [30, 41, 59],
            textColor: [255, 255, 255],
            fontStyle: 'bold',
            halign: 'center'
        },
        columnStyles: {
            0: { fontStyle: 'bold', fillColor: [250, 250, 250], cellWidth: 50 },
            1: { cellWidth: 'auto' }
        },
        styles: {
            fontSize: 10,
            cellPadding: 5,
            lineColor: [226, 232, 240], // bg-slate-200
            lineWidth: 0.1
        },
        margin: { left: 14, right: 14 }
    });

    // Footer
    const finalY = (doc as any).lastAutoTable.finalY + 20;
    if (finalY < 280) {
        doc.setFontSize(8);
        doc.setTextColor(150, 150, 150);
        doc.text("This report is automatically generated by the Inventory Management System. Data accurate as of time of generation.", 14, 285);
    }

    doc.save(`product-${product.lot || 'item'}-${product.id?.slice(0, 6)}.pdf`);
};
export const exportConsignmentPDF = (consignment: any) => {
    const doc = new jsPDF();

    // Header
    doc.setFontSize(22);
    doc.setTextColor(30, 41, 59);
    doc.text("IMPORT BATCH REPORT", 14, 20);

    doc.setFontSize(10);
    doc.setTextColor(148, 163, 184);
    doc.text(`Batch ID: #${consignment.id.slice(0, 8)}`, 14, 28);
    doc.text(`Lot: ${consignment.lot}`, 14, 33);
    doc.text(`Generated on: ${new Date().toLocaleString("th-TH")}`, 14, 38);

    doc.setDrawColor(226, 232, 240);
    doc.line(14, 42, 196, 42);

    // Consignor Info
    doc.setFontSize(12);
    doc.setTextColor(30, 41, 59);
    doc.text("Consignor Information", 14, 52);

    autoTable(doc, {
        startY: 55,
        body: [
            ["Name", consignment.consignorName],
            ["Contact", consignment.contactNumber],
            ["Address", consignment.address],
            ["Date", new Date(consignment.date).toLocaleDateString("th-TH")],
            ["Total Price", `฿${consignment.totalPrice?.toLocaleString()}`]
        ],
        theme: 'plain',
        styles: { fontSize: 10, cellPadding: 2 }
    });

    // Items Table
    doc.setFontSize(12);
    doc.text("Product Items", 14, (doc as any).lastAutoTable.finalY + 15);

    autoTable(doc, {
        startY: (doc as any).lastAutoTable.finalY + 20,
        head: [["No.", "Product Name", "Category", "Status", "Price"]],
        body: consignment.items.map((item: any, index: number) => [
            index + 1,
            item.productName,
            item.category,
            item.status,
            `฿${item.confirmedPrice?.toLocaleString()}`
        ]),
        theme: 'striped',
        headStyles: { fillColor: [220, 38, 38] }, // Red theme
        styles: { fontSize: 9 }
    });

    doc.save(`batch-${consignment.lot}-${consignment.consignorName}.pdf`);
};
